{% set version = "0.4.4.2" %}

package:
  name: msgpack-numpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/msgpack-numpy/msgpack-numpy-{{ version }}.tar.gz
  sha256: a1638108538aaba55bebaef9d847dfb3064bb1c829e68301716a6a956fa6a0d6

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.9.0
    - msgpack-python >=0.3.0

test:
  imports:
    - msgpack_numpy

about:
  home: https://github.com/lebedov/msgpack-numpy
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Numpy data serialization using msgpack
  description: |
    This package provides encoding and decoding routines that enable the
    serialization and deserialization of numerical and array data types
    provided by numpy using the highly efficient msgpack format. Serialization
    of Python's native complex data types is also supported.
  doc_url: https://pypi.python.org/pypi/msgpack-numpy
  dev_url: https://github.com/lebedov/msgpack-numpy

extra:
  recipe-maintainers:
    - nehaljwani
    - carlodri
