{% set version = "0.4.8" %}

package:
  name: msgpack-numpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/msgpack-numpy/msgpack-numpy-{{ version }}.tar.gz
  sha256: c667d3180513422f9c7545be5eec5d296dcbb357e06f72ed39cc683797556e69

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.9.0
    - msgpack-python >=0.5.2

test:
  imports:
    - msgpack_numpy

about:
  home: https://github.com/lebedov/msgpack-numpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Numpy data serialization using msgpack
  description: |
    This package provides encoding and decoding routines that enable the
    serialization and deserialization of numerical and array data types
    provided by numpy using the highly efficient msgpack format. Serialization
    of Python's native complex data types is also supported.
  doc_url: https://pypi.python.org/pypi/msgpack-numpy
  dev_url: https://github.com/lebedov/msgpack-numpy

extra:
  recipe-maintainers:
    - nehaljwani
    - carlodri
