{% set version = "0.4.4.3" %}

package:
  name: msgpack-numpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/msgpack-numpy/msgpack-numpy-{{ version }}.tar.gz
  sha256: a02c0069fb580c6a2dda9b98d40d34fda3840863112a5465ba9b54fa2ee005a5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.9.0
    - msgpack-python >=0.5.2

test:
  imports:
    - msgpack_numpy

about:
  home: https://github.com/lebedov/msgpack-numpy
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Numpy data serialization using msgpack
  description: |
    This package provides encoding and decoding routines that enable the
    serialization and deserialization of numerical and array data types
    provided by numpy using the highly efficient msgpack format. Serialization
    of Python's native complex data types is also supported.
  doc_url: https://pypi.python.org/pypi/msgpack-numpy
  dev_url: https://github.com/lebedov/msgpack-numpy

extra:
  recipe-maintainers:
    - nehaljwani
    - carlodri
