{% set version = "0.4.3" %}

package:
  name: msgpack-numpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/msgpack-numpy/msgpack-numpy-{{ version }}.tar.gz
  sha256: 9d6da0bbb04d7cab2bf9f08f78232c954f00ac95cf2384149e779a31ce859126

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy >=1.9.0
    - msgpack-python >=0.3.0

test:
  imports:
    - msgpack_numpy

about:
  home: https://github.com/lebedov/msgpack-numpy
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Numpy data serialization using msgpack
  description: |
    This package provides encoding and decoding routines that enable the
    serialization and deserialization of numerical and array data types
    provided by numpy using the highly efficient msgpack format. Serialization
    of Python's native complex data types is also supported.
  doc_url: https://pypi.python.org/pypi/msgpack-numpy
  dev_url: https://github.com/lebedov/msgpack-numpy

extra:
  recipe-maintainers:
    - nehaljwani
