travis:
  secure:
    BINSTAR_TOKEN: aD0GkU969b+OFnX9mhEhBIJHawy2nRPi2Isx05J3G5qy0BKoVUiZAGNw1B26NNJC3EMOQGl51YpT4dfbhDA+HrJn29vdtcQER9Bj4qpMnsEZvpBMSfjl1mC1yNOu+FOWjjqEg+LVw9ZMzYxK4hQj/ro7sgUKwD3xlVDyhyBOq2IPQlnwt10nGYK9GTcgG1yu7gI662Ct7s03e4fGxtWfWjob9V/fuN9EDtaYLz5uIT6BscGvkVCfL0E7AdmyTWNphOgvNc7wuS2pP4yesiqLrHjPMwF5sk7GMqxnyKYbzgRyOsjFG0DVqPWiHnfTwwWq76rEMwQGw+BWNqRekI8nkSbfyBZrd3Sz2H26cTEu9EPV18cUZFwzTjOdmprQXJR2vY64CjNQEdMp2nA3yhXFJiRoOFkfQPc2smOMKLL7JyF7KPZeeGZDZckZBns+3/aqc2bn61QbbgkAXAgH96no4Wl2EH2IVZG+ZPuI9EWTxaE2wG8l5JRxjoeBT3CpG7GcSQEjk0ORMWd2iCtDTpaUQ7DosGjNR5Q14vTKQOiTUctVLQniis8Oz5sZf76kwdqqBk5JqLQ2lDO6EL8mDa1bs1VoRRMsN89JnCVKpayEfjeh676oP9BKXLxvcbgMnAvbRan6RM3p+UWRncApd5gF6n7nIvl4JbDVf6fpQsmMBTo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
